global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  - job_name: "tracker_metrics"
    metrics_path: "/api/v1/stats"
    params:
      token: ["MyAccessToken"]
      format: ["prometheus"]
    static_configs:
      - targets: ["tracker:1212"]

